# Generated by Django 3.1.8 on 2023-06-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='budgets.budget', verbose_name='Budżet'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='categories.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='money_amount',
            field=models.PositiveIntegerField(verbose_name='Kwota'),
        ),
    ]
